### ISSUE TITLE
MISCALCULATION

### ISSUE THREAD

**Issue by Raolibec** [kisonecat/math-expressions#15]
`var a = MathExpression.fromLaTeX('a(a-b)-(ab-b)')`
`var b = MathExpression.fromLaTeX('a(a-b)-(-b+ab)')`
`a.equals(b);`
The result is false. but i think it should be true

**Comment by NishealJ** [comment]
Any update on this?

**Comment by dqnykamp** [comment]
I can't reproduce this error using any of the v2.0.0 builds.  I assume that this must be from of the 1.x versions.  It appears we fixed the flaw since then.
