### ISSUE TITLE
False positive in expression.equals

### ISSUE THREAD

**Issue by hczhcz** [kisonecat/math-expressions#4]
Example ("demo of math-expressions", tested under Firefox 45, Linux):

> Left hand side: `0`
> Right hand side: `x!`
> LHS = RHS? They are equal.

While these cases are correct:

> Left hand side: `0`
> Right hand side: `x!+1`
> LHS = RHS? They are not equal.
> 
> Left hand side: `0`
> Right hand side: `x!+n-n` // test real numbers
> LHS = RHS? They are not equal.

And:

> Left hand side: `0`
> Right hand side: `17^x`
> LHS = RHS? They are not equal.
> 
> Left hand side: `0`
> Right hand side: `18^x`
> LHS = RHS? They are equal.

It seems like something wrong happens when calculating complex numbers.

// Anyway, Ximera is cool! :-)

**Comment by dqnykamp** [comment]
These false positives do not exist in version 2.  (Online demo has not yet been updated.)
