### ISSUE TITLE
MathExpression.fromLatex() sometimes ignores parts of the input.

### ISSUE THREAD

**Issue by seanlip** [kisonecat/math-expressions#5]
Running the following command:

```
MathExpression.fromLatex('K \\cdot \\frac{q}{r}')
```

produces a StraightLineProgram whose syntax_tree is the single string "K", although the expression really represents K*q/r. The "frac" part seems to be ignored.

(This can also be reproduced at the [demo page](https://rawgit.com/kisonecat/math-expressions/master/demo/index.html) as of commit [10186a](https://github.com/kisonecat/math-expressions/tree/10186afeb160aa48ed94b20afd6353759c059dee).)

**Comment by kisonecat** [comment]
In 1bfaf8f68ed1c27c2c064fec8dfdcb97550abdc2 at least

```var f = Expression.fromLatex('K \\cdot \\frac{q}{r}');```

then `f.tex()` correctly outputs `K \, \left(\frac{q}{r}\right)`
