### ISSUE TITLE
Can't enter Greek letters

### ISSUE THREAD

**Issue by seanlip** [kisonecat/math-expressions#6]
I can't seem to find a way to enter Greek letters into the [demo](https://rawgit.com/kisonecat/math-expressions/master/demo/index.html) -- for example, expressions such as `\lambda * \pi`. The \lambda either ends up getting split into six single-character variables, or results in "TypeError: tree.slice is not a function".

**Comment by kisonecat** [comment]
That input box is set to accept text and not LaTeX, so words like "lambda" and "pi" (without the slash) should be correctly parsed.
![screenshot](https://cloud.githubusercontent.com/assets/148352/21493018/25fd2414-cbd7-11e6-8997-c7cf0f209846.png)
