### ISSUE TITLE
The index page for the demo does not work.

### ISSUE THREAD

**Issue by seanlip** [kisonecat/math-expressions#7]
When going to the demo at https://rawgit.com/kisonecat/math-expressions/master/demo/index.html, there is a console error:

```
uRequire: combined template 'lib', detected missing dependency `xml-parser` - all
it's known binding variables `parseString` were undefined
```

Typing things into the input boxes results in the error message "Left hand TeX: ReferenceError: MathExpression is not defined".

NB: this is the version corresponding to the commit https://github.com/kisonecat/math-expressions/commit/1bfaf8f68ed1c27c2c064fec8dfdcb97550abdc2.

**Comment by kisonecat** [comment]
This took me a bit longer to fix than I would have liked.

370a77f6a98974c14a37b4096bea88f8ec36797a resolves this by eliminating the xml-parser error.
